In [6]:
import numpy as np
import torch
import torch.nn.functional as F

dtype = torch.float
device = torch.device("cpu")
# N is batch size; D_in is input dimension;
N, D_out = 4, 6

# Version without pytorch
output = np.random.randn(N, D_out)

def my_softmax(nums):
    rst = np.exp(nums) / np.sum(np.exp(nums), axis=1).reshape(4,1)
    return rst

print(my_softmax(output))


# Version with pytorch
output = torch.randn(N, D_out, device=device, dtype=dtype)

print(output)
print(F.softmax(output, dim=1))
print(F.softmax(output, dim=1).sum(axis=1))  # Sums to 1 because it is a distribution!

[[ 0.33831645  0.05147664  0.36930843  0.01306616  0.19721669  0.03061562]
 [ 0.12990166  0.02830234  0.04680695  0.29846837  0.43243365  0.06408703]
 [ 0.43513154  0.17017453  0.14134381  0.13346777  0.09410005  0.02578231]
 [ 0.56612535  0.12441765  0.02089649  0.09421838  0.09350408  0.10083805]]
tensor([[ 1.2112, -0.2058, -0.2820, -0.6513, -1.8489, -0.5361],
        [ 0.7789,  0.1755,  1.1240,  0.4955, -0.8198,  0.2016],
        [ 2.6034,  0.2001, -0.2266,  0.3400, -0.5017,  0.1569],
        [-1.3248,  0.9990,  0.7850,  0.3226, -0.8547, -1.2602]])
tensor([[0.5424, 0.1315, 0.1219, 0.0842, 0.0254, 0.0945],
        [0.2234, 0.1222, 0.3155, 0.1683, 0.0452, 0.1254],
        [0.7221, 0.0653, 0.0426, 0.0751, 0.0324, 0.0625],
        [0.0366, 0.3739, 0.3018, 0.1901, 0.0586, 0.0390]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])


In [54]:
test = np.array([1,2,3,4])
print(test.shape)
# The following two are equivalent
# np.expand_dims(test, axis=1)
print(test[:,np.newaxis].shape)
print(test[np.newaxis,:].shape)

(4,)
(4, 1)
(1, 4)
